platform: linux
image_resource:
  type: docker-image
  source:
    repository: 192.168.1.227:5000/boot-build-home
    insecure_registries: ["192.168.1.227:5000"]
  
inputs:
- name: source-code
outputs:
- name: binaries
run:
  path: ./build.sh
  args:
  - binaries
  dir: source-code
